# Generated by Django 2.1.5 on 2019-11-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authen', '0003_auto_20191124_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution1', models.CharField(max_length=50)),
                ('solution2', models.CharField(max_length=100)),
                ('solution3', models.CharField(max_length=100)),
                ('solution4', models.CharField(max_length=100)),
                ('solution5', models.CharField(max_length=100)),
                ('solution6', models.CharField(max_length=100)),
                ('solution7', models.CharField(max_length=100)),
                ('solution8', models.CharField(max_length=100)),
                ('solution9', models.CharField(max_length=100)),
                ('solution10', models.CharField(max_length=100)),
                ('solution11', models.CharField(max_length=100)),
                ('solution12', models.CharField(max_length=100)),
                ('solution13', models.CharField(max_length=100)),
                ('solution14', models.CharField(max_length=100)),
                ('solution15', models.CharField(max_length=100)),
                ('solution16', models.CharField(max_length=100)),
                ('solution17', models.CharField(max_length=100)),
                ('solution18', models.CharField(max_length=100)),
                ('solution19', models.CharField(max_length=100)),
                ('solution20', models.CharField(max_length=100)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.Appuser')),
            ],
        ),
    ]
