# Generated by Django 2.1.5 on 2019-11-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_auto_20191124_0147'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.AddField(
            model_name='questions',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.Group'),
        ),
    ]
