# Generated by Django 2.1.5 on 2019-11-26 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20191121_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='topic5',
        ),
    ]
