# Generated by Django 2.1.5 on 2019-11-26 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_remove_preferences_topic5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='userid',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='authen.Appuser'),
        ),
    ]
