# Generated by Django 2.1.5 on 2019-11-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='subject1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='subject2',
            field=models.IntegerField(),
        ),
    ]
